### ISSUE TITLE
build fails on ninja with consistent error - undefined reference to `g_assert_cmpfloat_with_epsilon'

### ISSUE THREAD

**Issue by lreillywillhight** [gkarsay/parlatype#85]
### Installation and version

How did you install Parlatype?
   flatpak, and git clone, and distro package

* From git? If yes, please paste the output of `git log -1 --pretty=oneline`
* ' b6a0dfeaf847f58e2a8ed633fa622a63b324ca47 (HEAD -> main, origin/main, origin/HEAD) PtWindow: don't update time if time is unknown '

* From tarball? If yes, please paste the output of `parlatype --version`
bash: /usr/bin/parlatype: No such file or directory
(I get the same error installing from tarball)

* From a distro package?
NA

### Your desktop environment

* What's your distro? Mint 19.3
* What's your desktop environment?  Gnome
* If it's about LibreOffice helpers: What's your LibreOffice version? NA

### Issue

* What is not working as expected? Ninja build with tarball and git clone
* Does it happen all the time? Yes
* Did it work in the past (a regression)? NA
* What steps are needed to reproduce it? Meson build --prefix/usr ; cd build ; ninja
* If you start Parlatype from terminal, is there any error output? NA

### Other information

// FAILED: libparlatype/tests/config 

// /libparlatype/tests/config.c:253: undefined reference to `g_assert_cmpfloat_with_epsilon'

My system is a Thinkpad Yoga 400, which may have trouble with floating point calculation. Any help would be appreciated.

I can try updating Mint version, that may fix it if you released 2.1 in base repository. (Great program, by the way.)

**Comment by gkarsay** [comment]
Thanks for your report! Unfortunately it won't work on Mint 19.3 (which is based on Ubuntu 18.04). g_assert_cmpfloat_with_epsilon() was introduced to GLib in version 2.58 and you have 2.56. I will raise the minimum required version. That means you have to upgrade your system, unless you want to remove those calls for g_assert_cmpfloat_with_epsilon() manually. They are only for the test suite.

**Comment by lreillywillhight** [comment]
Ah, I should have thought of removing the test calls. Thanks!

**Comment by gkarsay** [comment]
Added a label that a fix was released: updated dependency version in the build system and in README.md.
